// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aero_sensor.proto
// Protobuf C++ Version: 4.25.4

#ifndef GOOGLE_PROTOBUF_INCLUDED_aero_5fsensor_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_aero_5fsensor_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_aero_5fsensor_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_aero_5fsensor_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_aero_5fsensor_2eproto;
namespace aero_sensor {
class aero_data;
struct aero_dataDefaultTypeInternal;
extern aero_dataDefaultTypeInternal _aero_data_default_instance_;
}  // namespace aero_sensor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aero_sensor {

// ===================================================================


// -------------------------------------------------------------------

class aero_data final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:aero_sensor.aero_data) */ {
 public:
  inline aero_data() : aero_data(nullptr) {}
  ~aero_data() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR aero_data(::google::protobuf::internal::ConstantInitialized);

  inline aero_data(const aero_data& from)
      : aero_data(nullptr, from) {}
  aero_data(aero_data&& from) noexcept
    : aero_data() {
    *this = ::std::move(from);
  }

  inline aero_data& operator=(const aero_data& from) {
    CopyFrom(from);
    return *this;
  }
  inline aero_data& operator=(aero_data&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const aero_data& default_instance() {
    return *internal_default_instance();
  }
  static inline const aero_data* internal_default_instance() {
    return reinterpret_cast<const aero_data*>(
               &_aero_data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(aero_data& a, aero_data& b) {
    a.Swap(&b);
  }
  inline void Swap(aero_data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(aero_data* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  aero_data* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<aero_data>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const aero_data& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const aero_data& from) {
    aero_data::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(aero_data* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "aero_sensor.aero_data";
  }
  protected:
  explicit aero_data(::google::protobuf::Arena* arena);
  aero_data(::google::protobuf::Arena* arena, const aero_data& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReadingsPaFieldNumber = 2,
  };
  // repeated float readings_pa = 2;
  int readings_pa_size() const;
  private:
  int _internal_readings_pa_size() const;

  public:
  void clear_readings_pa() ;
  float readings_pa(int index) const;
  void set_readings_pa(int index, float value);
  void add_readings_pa(float value);
  const ::google::protobuf::RepeatedField<float>& readings_pa() const;
  ::google::protobuf::RepeatedField<float>* mutable_readings_pa();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_readings_pa() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_readings_pa();

  public:
  // @@protoc_insertion_point(class_scope:aero_sensor.aero_data)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<float> readings_pa_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_aero_5fsensor_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// aero_data

// repeated float readings_pa = 2;
inline int aero_data::_internal_readings_pa_size() const {
  return _internal_readings_pa().size();
}
inline int aero_data::readings_pa_size() const {
  return _internal_readings_pa_size();
}
inline void aero_data::clear_readings_pa() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.readings_pa_.Clear();
}
inline float aero_data::readings_pa(int index) const {
  // @@protoc_insertion_point(field_get:aero_sensor.aero_data.readings_pa)
  return _internal_readings_pa().Get(index);
}
inline void aero_data::set_readings_pa(int index, float value) {
  _internal_mutable_readings_pa()->Set(index, value);
  // @@protoc_insertion_point(field_set:aero_sensor.aero_data.readings_pa)
}
inline void aero_data::add_readings_pa(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_readings_pa()->Add(value);
  // @@protoc_insertion_point(field_add:aero_sensor.aero_data.readings_pa)
}
inline const ::google::protobuf::RepeatedField<float>& aero_data::readings_pa() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aero_sensor.aero_data.readings_pa)
  return _internal_readings_pa();
}
inline ::google::protobuf::RepeatedField<float>* aero_data::mutable_readings_pa()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:aero_sensor.aero_data.readings_pa)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_readings_pa();
}
inline const ::google::protobuf::RepeatedField<float>& aero_data::_internal_readings_pa()
    const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.readings_pa_;
}
inline ::google::protobuf::RepeatedField<float>* aero_data::_internal_mutable_readings_pa() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.readings_pa_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace aero_sensor


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_aero_5fsensor_2eproto_2epb_2eh
