// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aero_sensor.proto

#include "aero_sensor.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aero_sensor {

inline constexpr aero_data::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : readings_pa_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR aero_data::aero_data(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct aero_dataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR aero_dataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~aero_dataDefaultTypeInternal() {}
  union {
    aero_data _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 aero_dataDefaultTypeInternal _aero_data_default_instance_;
}  // namespace aero_sensor
static ::_pb::Metadata file_level_metadata_aero_5fsensor_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_aero_5fsensor_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_aero_5fsensor_2eproto = nullptr;
const ::uint32_t TableStruct_aero_5fsensor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::aero_sensor::aero_data, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::aero_sensor::aero_data, _impl_.readings_pa_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::aero_sensor::aero_data)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::aero_sensor::_aero_data_default_instance_._instance,
};
const char descriptor_table_protodef_aero_5fsensor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021aero_sensor.proto\022\013aero_sensor\" \n\taero"
    "_data\022\023\n\013readings_pa\030\002 \003(\002b\006proto3"
};
static ::absl::once_flag descriptor_table_aero_5fsensor_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_aero_5fsensor_2eproto = {
    false,
    false,
    74,
    descriptor_table_protodef_aero_5fsensor_2eproto,
    "aero_sensor.proto",
    &descriptor_table_aero_5fsensor_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_aero_5fsensor_2eproto::offsets,
    file_level_metadata_aero_5fsensor_2eproto,
    file_level_enum_descriptors_aero_5fsensor_2eproto,
    file_level_service_descriptors_aero_5fsensor_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_aero_5fsensor_2eproto_getter() {
  return &descriptor_table_aero_5fsensor_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_aero_5fsensor_2eproto(&descriptor_table_aero_5fsensor_2eproto);
namespace aero_sensor {
// ===================================================================

class aero_data::_Internal {
 public:
};

aero_data::aero_data(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aero_sensor.aero_data)
}
inline PROTOBUF_NDEBUG_INLINE aero_data::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : readings_pa_{visibility, arena, from.readings_pa_},
        _cached_size_{0} {}

aero_data::aero_data(
    ::google::protobuf::Arena* arena,
    const aero_data& from)
    : ::google::protobuf::Message(arena) {
  aero_data* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:aero_sensor.aero_data)
}
inline PROTOBUF_NDEBUG_INLINE aero_data::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : readings_pa_{visibility, arena},
        _cached_size_{0} {}

inline void aero_data::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
aero_data::~aero_data() {
  // @@protoc_insertion_point(destructor:aero_sensor.aero_data)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void aero_data::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void aero_data::Clear() {
// @@protoc_insertion_point(message_clear_start:aero_sensor.aero_data)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.readings_pa_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* aero_data::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> aero_data::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_aero_data_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated float readings_pa = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(aero_data, _impl_.readings_pa_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float readings_pa = 2;
    {PROTOBUF_FIELD_OFFSET(aero_data, _impl_.readings_pa_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* aero_data::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aero_sensor.aero_data)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float readings_pa = 2;
  if (this->_internal_readings_pa_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_readings_pa(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aero_sensor.aero_data)
  return target;
}

::size_t aero_data::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aero_sensor.aero_data)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float readings_pa = 2;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_readings_pa_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData aero_data::_class_data_ = {
    aero_data::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* aero_data::GetClassData() const {
  return &_class_data_;
}

void aero_data::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<aero_data*>(&to_msg);
  auto& from = static_cast<const aero_data&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aero_sensor.aero_data)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_readings_pa()->MergeFrom(from._internal_readings_pa());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void aero_data::CopyFrom(const aero_data& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aero_sensor.aero_data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool aero_data::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* aero_data::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void aero_data::InternalSwap(aero_data* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.readings_pa_.InternalSwap(&other->_impl_.readings_pa_);
}

::google::protobuf::Metadata aero_data::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_aero_5fsensor_2eproto_getter, &descriptor_table_aero_5fsensor_2eproto_once,
      file_level_metadata_aero_5fsensor_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace aero_sensor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
